
#
# This file is used for configuring Python tools, rather than
# the workspace as a whole. As uv supports workspace it will be used.
#


# Pylint configuration
[tool.pylint]

# Source roots - important for finding imports
source-roots = [
    "components/processing/libs/processor-base/src",
    "components/processing/libs/processor-msg/src",
    "components/processing/libs/processor-xlsx/src",
    "components/forms-classifier/src",
    "components/webui/src",
]

[tool.pylint."MESSAGE_CONTROL"]

# Disable everything
disable="all"

# But enable warnings and unused-import
enable="E,unused-import"


# Pyright configuration
[tool.pyright]

# Paths of files to validate
include=[
    "components/processing/libs/processor-base/src",
    "components/processing/libs/processor-msg/src",
    "components/processing/libs/processor-xlsx/src",
    "components/forms-classifier/src",
    "components/webui/src",
]

# Paths of modules for dependencies
executionEnvironments = [
    { root = ".", extraPaths = [
        "components/processing/libs/processor-xlsx/src",
        "components/processing/libs/processor-base/src",
        "components/processing/libs/processor-msgx/src",
        "components/forms-classifier/src",
        "components/webui/src",
        ]
    }
]

reportMissingImports=true
reportMissingTypeStubs=false

